# Generated by Django 3.2.6 on 2021-08-29 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='music')),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.CharField(choices=[('dep', 'dep'), ('deephouse', 'deephouse')], max_length=10)),
                ('Boolean', models.BooleanField(default=False)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
