# Generated by Django 3.1.7 on 2021-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_auto_20210904_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ip_adress',
            field=models.ManyToManyField(related_name='ip_adress', to='Music.IpAdress'),
        ),
    ]
