# Generated by Django 3.1.7 on 2021-09-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_auto_20210904_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ip_adress',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Music.IpAdress'),
        ),
    ]
