# Generated by Django 3.1.7 on 2021-09-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20210904_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ip_adress',
            new_name='hits',
        ),
    ]
