# Generated by Django 3.1.7 on 2021-09-04 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_remove_blog_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.blog')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.ipadress')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='Music.Article', to='Music.IpAdress'),
        ),
    ]
