# Generated by Django 3.1.7 on 2021-09-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_auto_20210904_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipadress',
            old_name='ipadress',
            new_name='ipaddress',
        ),
    ]
