# Generated by Django 3.2.6 on 2021-09-05 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_auto_20210905_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('create', models.DateTimeField(default=datetime.datetime(2021, 9, 5, 6, 42, 14, 251518, tzinfo=utc))),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Music.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
