# Generated by Django 3.2.6 on 2021-09-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0013_alter_comment_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hits',
        ),
    ]
