# Generated by Django 3.2.6 on 2021-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0015_auto_20210905_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=30),
        ),
    ]
