# Generated by Django 3.2.6 on 2021-09-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0016_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipadress',
            old_name='ipaddress',
            new_name='ip_address',
        ),
    ]
