# Generated by Django 3.2.6 on 2021-09-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0019_rename_title_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=models.CharField(max_length=50),
        ),
    ]
