# Generated by Django 3.2.6 on 2021-09-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0020_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='File',
            field=models.FileField(blank=True, upload_to='file'),
        ),
    ]
