# Generated by Django 3.2.6 on 2021-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0025_auto_20210913_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='File',
            field=models.FileField(upload_to='file'),
        ),
    ]
