# Generated by Django 3.2.6 on 2021-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0026_alter_blog_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ManyToManyField(to='Music.Blog')),
            ],
        ),
    ]
