# Generated by Django 3.2.6 on 2021-09-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0028_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ip_address',
        ),
        migrations.DeleteModel(
            name='IpAddress',
        ),
        migrations.RemoveField(
            model_name='main',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Music.IpAdress'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
