# Generated by Django 3.2.6 on 2021-09-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0029_auto_20210914_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hits',
        ),
    ]
