# Generated by Django 3.2.6 on 2021-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0030_remove_blog_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Music.IpAdress'),
        ),
    ]
