# Generated by Django 3.2.6 on 2021-09-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0031_blog_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hits',
        ),
        migrations.DeleteModel(
            name='IpAdress',
        ),
    ]
