# Generated by Django 3.2.6 on 2021-09-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0033_auto_20210914_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
